image: java:8-jdk

stages:
- build
- test

before_script:
- export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
  - .gradle/wrapper/
  - .gradle/caches/

build:
  stage: build
  tags:
    - docker
  script:
  - ./gradlew clean assemble
  artifacts:
    paths:
    - build/distributions/*.zip
    expire_in: 1 week
  only:
  - master

build-2018.2:
  stage: build
  tags:
    - docker
  script:
  - ./gradlew clean assemble -PideaVersion=IC-2018.2
  only:
  - master

build-2018.3:
  stage: build
  tags:
    - docker
  script:
  - ./gradlew clean assemble -PideaVersion=IC-2018.3
  only:
  - master

test:
  stage: test
  tags:
    - docker
  script:
  - ./gradlew clean check

test-2018.2:
  stage: test
  tags:
    - docker
  script:
  - ./gradlew clean check -PideaVersion=IC-2018.2

test-2018.3:
  stage: test
  tags:
    - docker
  script:
  - ./gradlew clean check -PideaVersion=IC-2018.3

after_script:
- echo "End CI"